# =================Training Commands==================================== #
train_volseg_unet:
	python src/volseg_interface.py volseg_unet.yaml

# =================Inferencing Commands==================================== #
segment_volseg_unet:
	python src/volseg_interface.py volseg_unet.yaml

